### ISSUE TITLE
1.18.2 Version is tagged 1.18.1

### ISSUE THREAD

**Issue by Marcarrones** [Clooooud/buildertb#2]
Got this crash:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BuilderTB' (buildertb) 1.0-SNAPSHOT with any version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'BuilderTB' (buildertb) 1.0-SNAPSHOT requires version 1.18.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
It seems you forgot to change the version?:

https://github.com/Clooooud/buildertb/blob/1.18/gradle.properties

**Comment by Marcarrones** [comment]
Don't know how to build a mod, otherwise I'd give it a shot
